### ISSUE TITLE
Mac环境下  npm start 的时候报错了

### ISSUE THREAD

**Issue by Geek-James** [liupeijun/vue2-hybridapp-haoshiqi#1]
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! backend@0.0.0 start: `node-dev ./bin/www`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the backend@0.0.0 start script 'node-dev ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the backend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-dev ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs backend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls backend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/James/Desktop/Vue+NodeJs+Cordever/vue2-hybridapp-haoshiqi-master/backend/npm-debug.log

**Comment by Geek-James** [comment]
大神 帮忙看下 在mac环境下运行你的项目，运行node start的时候报错  Mac环境 node.js版本是v6.9.4 npm版本是3.10.10

**Comment by liupeijun** [comment]
npm  start 执行的是 node-dev ./bin/www , 是否安装node-dev

**Comment by Geek-James** [comment]
已经解决  是没有安装 npm -dev 造成的 感谢大神！！
